development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  host : localhost
  username: exemple
  password: exemple

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  host : localhost
  username: exemple
  password: exemple

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  username:
  password:

cucumber:
  <<: *TEST